// @flow
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SHOW_BURGER_MENU = "SHOW_BURGER_MENU";
export const HIDE_BURGER_MENU = "HIDE_BURGER_MENU";

export const ADD_FAV_ARTICLE = "ADD_FAV_ARTICLE";
export const REMOVE_FAV_ARTICLE = "REMOVE_FAV_ARTICLE";
