// @flow
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const DELETE_USER = "DELETE_USER";

export const SHOW_BURGER_MENU = "SHOW_BURGER_MENU";
export const HIDE_BURGER_MENU = "HIDE_BURGER_MENU";
export const SHOW_POPUP = "SHOW_POPUP";

export const ADD_FAV_ARTICLE = "ADD_FAV_ARTICLE";
export const REMOVE_FAV_ARTICLE = "REMOVE_FAV_ARTICLE";

export const ADD_FAV_SERVICE = "ADD_FAV_SERVICE";
export const REMOVE_FAV_SERVICE = "REMOVE_FAV_SERVICE";
