repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
        args:
        - --max-line-length=120
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6.8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8